name: Test Artifact Download Feature

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: read  # Needed for artifact access

jobs:
  generate-and-upload-images:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      with:
        lfs: true
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Python for test execution
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: '3.x'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate test images
      run: |
        export TEST_SCENARIO="baseline"
        echo "Generating test images for artifact download test..."
        python generate_test_images.py
    
    - name: Verify test images were generated
      run: |
        if [ ! -d "outputs" ] || [ -z "$(ls -A outputs/ 2>/dev/null)" ]; then
          echo "❌ Test image generation failed - no outputs found"
          exit 1
        fi
        
        IMAGE_COUNT=$(ls -1 outputs/*.png 2>/dev/null | wc -l)
        echo "✅ Generated $IMAGE_COUNT test images for artifact download test"
        ls -la outputs/
    
    - name: Upload test images as artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-images-for-artifact-download
        path: outputs/
        retention-days: 1
        if-no-files-found: error

  test-artifact-download-workflow:
    needs: generate-and-upload-images
    uses: ./.github/workflows/visual-diff.yml
    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: read
    with:
      outputs_directory: 'outputs'
      artifact_name: 'test-images-for-artifact-download'
      artifact_suffix: 'artifact-test'

  test-backward-compatibility:
    uses: ./.github/workflows/visual-diff.yml
    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: read
    with:
      outputs_directory: 'outputs'
      test_mode: true
      artifact_suffix: 'compatibility-test'
      # artifact_name is intentionally not provided to test backward compatibility

  validate-tests:
    runs-on: ubuntu-latest
    needs: [test-artifact-download-workflow, test-backward-compatibility]
    if: always()
    
    steps:
    - name: Validate test results
      run: |
        echo "# Artifact Download Feature Test Results" > test_results.md
        echo "" >> test_results.md
        echo "**Test Run:** $(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> test_results.md
        echo "" >> test_results.md
        
        # Check if both test jobs succeeded
        ARTIFACT_TEST_RESULT="${{ needs.test-artifact-download-workflow.result }}"
        COMPAT_TEST_RESULT="${{ needs.test-backward-compatibility.result }}"
        
        echo "## Test Results Summary" >> test_results.md
        echo "" >> test_results.md
        echo "| Test | Status | Result |" >> test_results.md
        echo "|------|--------|--------|" >> test_results.md
        echo "| Artifact Download | $ARTIFACT_TEST_RESULT | $([ "$ARTIFACT_TEST_RESULT" = "success" ] && echo "✅ PASSED" || echo "❌ FAILED") |" >> test_results.md
        echo "| Backward Compatibility | $COMPAT_TEST_RESULT | $([ "$COMPAT_TEST_RESULT" = "success" ] && echo "✅ PASSED" || echo "❌ FAILED") |" >> test_results.md
        echo "" >> test_results.md
        
        # Overall result
        if [ "$ARTIFACT_TEST_RESULT" = "success" ] && [ "$COMPAT_TEST_RESULT" = "success" ]; then
          echo "## ✅ All Tests Passed" >> test_results.md
          echo "" >> test_results.md
          echo "The artifact download feature is working correctly and maintains backward compatibility:" >> test_results.md
          echo "- **Artifact Download Test**: Successfully downloaded and processed images from artifact" >> test_results.md
          echo "- **Backward Compatibility Test**: Existing workflow patterns continue to work without changes" >> test_results.md
          echo "" >> test_results.md
          echo "The feature is ready for production use." >> test_results.md
          
          echo "✅ All artifact download feature tests passed"
          ALL_PASSED=true
        else
          echo "## ❌ Some Tests Failed" >> test_results.md
          echo "" >> test_results.md
          echo "The artifact download feature has issues that need to be addressed:" >> test_results.md
          echo "" >> test_results.md
          if [ "$ARTIFACT_TEST_RESULT" != "success" ]; then
            echo "- **Artifact Download Test Failed**: The new artifact download functionality is not working correctly" >> test_results.md
          fi
          if [ "$COMPAT_TEST_RESULT" != "success" ]; then
            echo "- **Backward Compatibility Test Failed**: The changes broke existing workflow patterns" >> test_results.md
          fi
          echo "" >> test_results.md
          echo "Please review the test failures and fix the issues before merging." >> test_results.md
          
          echo "❌ Artifact download feature tests failed"
          ALL_PASSED=false
        fi
        
        cat test_results.md
        
        # Fail the workflow if tests failed
        if [ "$ALL_PASSED" = "false" ]; then
          exit 1
        fi
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: artifact-download-test-results
        path: test_results.md
        retention-days: 7